<div class="progos-cartweight"data-bind="scope: 'section'">
         Total Cart Weight: <span data-bind="text: cartweight().cartweight"></span>
</div>

<script type="text/x-magento-init">
    {
        "*":{
            "Magento_Ui/js/core/app":{
                "components":{
                    "section":{
                        "component":"Progos_CartWeightTabPDP/js/section"
                    }
                }
            }
        }
    }
</script>